# -*- coding: utf-8 -*-
"""Task3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GRbU0ocTcBjQ4Ngr5tszTpNLh29gnDIb
"""

from google.colab import drive
drive.mount('/content/drive')

task3_input = open(file = '/content/drive/MyDrive/CSE221/Lab 08/input3.txt', mode = 'r')

task3_output = open(file = '/content/drive/MyDrive/CSE221/Lab 08/output3.txt', mode = 'w')

lst = task3_input.readline().strip().split()
c, x = int(lst[0]), int(lst[1])
coin = task3_input.readline().strip().split()
for i in range(c):
  coin[i] = int(coin[i])

def min_coins(coins, target):
    coins.sort(reverse=True)
    count = 0
    for i in coins:
        while target >= i:
            target -= i
            count += 1
    if target == 0:
      return count
    else:
      return -1

task3_output.write(str(min_coins(coin, x)))

task3_input.close()
task3_output.close()