# -*- coding: utf-8 -*-
"""Task4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1E160ocY8nE68urNxOJ-xdmIOiqe-oBob
"""

from google.colab import drive
drive.mount('/content/drive')

task4_input = open(file='/content/drive/MyDrive/CSE221/Lab 04/input4.txt', mode='r')

task4_output = open(file='/content/drive/MyDrive/CSE221/Lab 04/output4.txt', mode='w')

lst = task4_input.readline().strip().split(" ")
v = int(lst[0])
e = int(lst[1])
adj_list = {}
for i in range(1, v+1):
    adj_list[i] = []
for i in range(e):
    lst2 = task4_input.readline().strip().split()
    u = int(lst2[0])
    v = int(lst2[1])
    adj_list[u].append(v)

def has_cycle(graph):
    color = {}
    p = {}
    time = 0
    d = {}
    f = {}
    for v in graph:
        color[v] = 'white'
        p[v] = None
        d[v] = 0
        f[v] = 0
    for u in graph:
        if color[u] == 'white':
            if dfs_visit(graph, u, color, p, d, f, time):
                return True
    return False

def dfs_visit(graph, u, color, p, d, f, time):
    stack = []
    stack.append(u)
    while len(stack) != 0:
        u = stack.pop()
        if color[u] == 'white':
            color[u] = 'gray'
            time += 1
            d[u] = time
            for v in graph[u]:
                if color[v] == 'white':
                    p[v] = u
                    stack.append(v)
                elif color[v] != 'white':
                    return True
            color[u] = 'black'
            time += 1
            f[u] = time
    return False

if has_cycle(adj_list):
    task4_output.write("YES")
else:
    task4_output.write("No")

task4_input.close()
task4_output.close()