# -*- coding: utf-8 -*-
"""Task2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mwair-rq7VIpdL_ChdABwAjgg10FW62_
"""

from google.colab import drive
drive.mount('/content/drive')

task2_input = open(file = '/content/drive/MyDrive/CSE221/Lab 08/input2.txt', mode = 'r')

task2_output = open(file = '/content/drive/MyDrive/CSE221/Lab 08/output2.txt', mode = 'w')

stairs = int(task2_input.readline().strip())

def ways_to_climb(n):
    if n == 0:
        return 1
    if n == 1:
        return 1
    arr = [0] * (n + 1)
    arr[0] = 1
    arr[1] = 1
    for i in range(2, n + 1):
        arr[i] = arr[i - 1] + arr[i - 2]
    return arr[n]

task2_output.write(str(ways_to_climb(stairs)))

task2_input.close()
task2_output.close()